version: "3"

services:
  i4ins:
    build:
      context: .
    container_name: i4ins
    image: asolodkov/i4ins
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://host.docker.internal:27017/ftns
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - "3000:3000"

networks:
  app-network:
    driver: bridge
